name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
  
jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build ios --release
      - run: ls -alh build/app/outputs

      - uses: actions/upload-artifact@v3
        with:
         name: stasi iobuild
         path: "build/app/outputs/flutter-ipa/app-*.ipa"

      - uses: alexellis/upload-assets@0.4.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["build/app/outputs/flutter-ipa/app-*.ipa"]'
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --release --split-per-abi

      - uses: actions/upload-artifact@v3
        with:
         name: stasi apk
         path: "build/app/outputs/flutter-apk/app-*.apk"

      - uses: alexellis/upload-assets@0.4.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["build/app/outputs/flutter-apk/app-*.apk"]'
